import { join, resolve } from "node:path";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";

// The @mill/sdk runtime source, by a layout-stable path (works on host + in the image),
// so Bun.build can inline it into the standalone bundle regardless of node_modules layout.
const SDK_PATH = resolve(import.meta.dir, "../../../packages/sdk/src/index.ts");
import { buildPlan } from "@mill/compiler";
import { loadProject, listWorkflows, loadWorkflow } from "@mill/projectfs";

// Export a project as a standalone, runnable JS bundle (ARCHITECTURE §7). The generated
// entry embeds every workflow's compiled plan + imports its node code + the @mill/sdk
// interpreter; `Bun.build` bundles it all into one self-contained index.js. That's the
// "compiles to one JS program" thesis: editor engine == server engine == export format.

function generateEntry(projectName: string, plans: Record<string, unknown>, imports: string[], nodeMap: string[], triggers: Record<string, string[]>, defaultWf: string, sdkPath: string): string {
  return `// Standalone bundle for the "${projectName}" project — generated by Mill.
// Two run modes:
//   batch : bun run index.js <workflow> '<json-input>'   → runs once, prints the result
//   server: bun run index.js serve [port]                → HTTP API, POST /run/<workflow>
${imports.join("\n")}
import { executePlan } from ${JSON.stringify(sdkPath)};

const PLANS = ${JSON.stringify(plans)};
const TRIGGERS = ${JSON.stringify(triggers)};
const NODES = {
${nodeMap.join("\n")}
};
const WORKFLOWS = Object.keys(PLANS);
const resolveRef = (ref) => (ref.startsWith("workflows/") ? ref.slice("workflows/".length) : ref);

async function runWorkflow(name, input) {
  const plan = PLANS[name];
  if (!plan) throw new Error("unknown workflow: " + name);
  const r = await executePlan(plan, {
    input,
    secrets: process.env,
    loadNode: async (node) => NODES[name + "/" + node.key],
    callScript: async (call, cin) => runWorkflow(resolveRef(call.ref), cin),
    onEvent: (e) => { if (process.env.MILL_VERBOSE) console.error(JSON.stringify(e)); },
  });
  return r.result;
}

function serve(port) {
  const server = Bun.serve({
    port,
    async fetch(req) {
      const path = new URL(req.url).pathname;
      if (req.method === "GET" && (path === "/" || path === "/health")) {
        return Response.json({ ok: true, project: ${JSON.stringify(projectName)}, workflows: WORKFLOWS.map((w) => ({ name: w, triggers: TRIGGERS[w] || [] })) });
      }
      const m = path.match(/^\\/(?:run|hooks)\\/(.+)$/);
      if (req.method === "POST" && m) {
        const name = decodeURIComponent(m[1]);
        if (!PLANS[name]) return Response.json({ error: "unknown workflow: " + name }, { status: 404 });
        let input = {};
        try { const t = await req.text(); input = t ? JSON.parse(t) : {}; } catch { return Response.json({ error: "invalid JSON body" }, { status: 400 }); }
        try { return Response.json({ status: "succeeded", workflow: name, result: await runWorkflow(name, input) }); }
        catch (e) { return Response.json({ status: "failed", workflow: name, error: String(e && e.message || e) }, { status: 500 }); }
      }
      return Response.json({ error: "not found", routes: ["GET /health", "POST /run/:workflow", "POST /hooks/:workflow"] }, { status: 404 });
    },
  });
  console.error("mill bundle '${projectName}' serving on http://localhost:" + server.port + " — POST /run/<workflow>");
  console.error("workflows: " + WORKFLOWS.join(", "));
}

const args = process.argv.slice(2);
if (args[0] === "serve") {
  serve(Number(args[1] || process.env.PORT || 8080));
} else {
  const [wf, inputJson] = args;
  runWorkflow(wf || ${JSON.stringify(defaultWf)}, inputJson ? JSON.parse(inputJson) : {})
    .then((r) => console.log(JSON.stringify(r)))
    .catch((e) => { console.error(String(e && e.message || e)); process.exit(1); });
}
`;
}

// Self-contained runner: it does EVERYTHING needed — checks for Bun, installs the bundle's
// npm deps on first run, then executes. Works from any cwd. Batch or server mode:
//   ./run.sh <workflow> '<json-input>'    ./run.sh serve [port]
const RUN_SH = `#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v bun >/dev/null 2>&1; then
  echo "This bundle needs Bun. Install it, then re-run:" >&2
  echo "  curl -fsSL https://bun.sh/install | bash" >&2
  exit 1
fi

# Install external dependencies once (no-op if the node code uses only the standard library).
if [ ! -f .mill-installed ]; then
  echo "mill: installing dependencies…" >&2
  bun install
  touch .mill-installed
fi

# Run: no args → first workflow (batch); "<workflow> '<json>'" → that workflow; "serve [port]" → HTTP API.
exec bun run index.js "$@"
`;

function readme(projectName: string, workflows: string[]): string {
  return `# ${projectName} — exported from Mill

A standalone bundle. Runs the same compiled program Mill runs. **\`run.sh\` does everything
required** — it checks for Bun, installs npm dependencies on first run, then executes. You
only need Bun installed (\`curl -fsSL https://bun.sh/install | bash\`).

## Run (batch — some jobs just run)
\`\`\`bash
./run.sh ${workflows[0] ?? "workflow"} '{}'      # runs once, prints the result
./run.sh                          # runs the first workflow with {} input
\`\`\`

## Serve as an HTTP API (others expose a port)
\`\`\`bash
./run.sh serve 8080
curl -s localhost:8080/health                       # → { ok, workflows: [...] }
curl -s -XPOST localhost:8080/run/${workflows[0] ?? "workflow"} -d '{}'   # → { status, result }
\`\`\`
\`POST /run/<workflow>\` (alias \`/hooks/<workflow>\`) runs a workflow with the JSON body as
input — the same entrypoint a webhook trigger would hit.

Workflows: ${workflows.join(", ")}.
Secrets are read from the environment (each node sees only the refs it declares).
`;
}

export async function exportProject(projectDir: string): Promise<{ tgz: Uint8Array; name: string }> {
  const proj = loadProject(projectDir);
  const wfNames = listWorkflows(projectDir);
  if (wfNames.length === 0) throw new Error("project has no workflows");

  const plans: Record<string, unknown> = {};
  const triggers: Record<string, string[]> = {};
  const imports: string[] = [];
  const nodeMap: string[] = [];
  const deps: Record<string, string> = {};
  let idx = 0;

  for (const name of wfNames) {
    const { def, dir } = loadWorkflow(projectDir, name);
    plans[name] = buildPlan(def);
    triggers[name] = (def.triggers ?? []).map((t) => t.type);
    for (const n of def.nodes) {
      // jscode nodes AND loop nodes with a per-item jscode body both import their .js file.
      if ((n.kind === "jscode" || n.kind === "loop") && n.file) {
        const v = `nfn${idx++}`;
        imports.push(`import ${v} from ${JSON.stringify(resolve(dir, n.file))};`);
        nodeMap.push(`  ${JSON.stringify(`${name}/${n.key}`)}: ${v},`);
      }
      if (n.deps) Object.assign(deps, n.deps);
    }
  }

  const tmp = mkdtempSync(join(tmpdir(), "mill-export-"));
  const out = mkdtempSync(join(tmpdir(), "mill-bundle-"));
  try {
    const entryPath = join(tmp, "entry.ts");
    writeFileSync(entryPath, generateEntry(proj.metadata.name, plans, imports, nodeMap, triggers, wfNames[0], SDK_PATH));

    const built = await Bun.build({ entrypoints: [entryPath], target: "bun", external: Object.keys(deps) });
    if (!built.success) throw new Error("bundle failed: " + built.logs.map((l) => String(l.message ?? l)).join("; "));
    const indexJs = await built.outputs[0].text();

    writeFileSync(join(out, "index.js"), indexJs);
    writeFileSync(join(out, "package.json"), JSON.stringify({ name: proj.metadata.name, private: true, type: "module", dependencies: deps, scripts: { start: "bun run index.js", "start-server": "bun run index.js serve" } }, null, 2));
    writeFileSync(join(out, "run.sh"), RUN_SH, { mode: 0o755 });
    writeFileSync(join(out, "README.md"), readme(proj.metadata.name, wfNames));

    const tgzPath = join(out, "bundle.tgz");
    await Bun.spawn(["tar", "-czf", tgzPath, "-C", out, "index.js", "package.json", "run.sh", "README.md"]).exited;
    const tgz = new Uint8Array(await Bun.file(tgzPath).arrayBuffer());
    return { tgz, name: proj.metadata.name };
  } finally {
    rmSync(tmp, { recursive: true, force: true });
    rmSync(out, { recursive: true, force: true });
  }
}
