import { join, resolve } from "node:path";
import { mkdtempSync, writeFileSync, rmSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";

// The @mill/sdk runtime source, by a layout-stable path (works on host + in the image),
// so Bun.build can inline it into the standalone bundle regardless of node_modules layout.
const SDK_PATH = resolve(import.meta.dir, "../../../packages/sdk/src/index.ts");
import { buildPlan } from "@mill/compiler";
import { loadProject, listWorkflows, loadWorkflow } from "@mill/projectfs";

// Export a project as a standalone, runnable JS bundle (ARCHITECTURE §7). The generated
// entry embeds every workflow's compiled plan + imports its node code + the @mill/sdk
// interpreter; `Bun.build` bundles it all into one self-contained index.js. That's the
// "compiles to one JS program" thesis: editor engine == server engine == export format.

function generateEntry(projectName: string, plans: Record<string, unknown>, imports: string[], nodeMap: string[], triggers: Record<string, string[]>, defaultWf: string, sdkPath: string): string {
  return `// Standalone bundle for the "${projectName}" project — generated by Mill.
// Two run modes:
//   batch : bun run index.js <workflow> '<json-input>'   → runs once, prints the result
//   server: bun run index.js serve [port]                → HTTP API, POST /run/<workflow>
${imports.join("\n")}
import { executePlan } from ${JSON.stringify(sdkPath)};

const PLANS = ${JSON.stringify(plans)};
const TRIGGERS = ${JSON.stringify(triggers)};
const NODES = {
${nodeMap.join("\n")}
};
const WORKFLOWS = Object.keys(PLANS);
const resolveRef = (ref) => (ref.startsWith("workflows/") ? ref.slice("workflows/".length) : ref);

async function runWorkflow(name, input) {
  const plan = PLANS[name];
  if (!plan) throw new Error("unknown workflow: " + name);
  const r = await executePlan(plan, {
    input,
    secrets: process.env,
    loadNode: async (node) => NODES[name + "/" + node.key],
    callScript: async (call, cin) => runWorkflow(resolveRef(call.ref), cin),
    onEvent: (e) => { if (process.env.MILL_VERBOSE) console.error(JSON.stringify(e)); },
  });
  return r.result;
}

function serve(port) {
  const server = Bun.serve({
    port,
    async fetch(req) {
      const path = new URL(req.url).pathname;
      if (req.method === "GET" && (path === "/" || path === "/health")) {
        return Response.json({ ok: true, project: ${JSON.stringify(projectName)}, workflows: WORKFLOWS.map((w) => ({ name: w, triggers: TRIGGERS[w] || [] })) });
      }
      const m = path.match(/^\\/(?:run|hooks)\\/(.+)$/);
      if (req.method === "POST" && m) {
        const name = decodeURIComponent(m[1]);
        if (!PLANS[name]) return Response.json({ error: "unknown workflow: " + name }, { status: 404 });
        let input = {};
        try { const t = await req.text(); input = t ? JSON.parse(t) : {}; } catch { return Response.json({ error: "invalid JSON body" }, { status: 400 }); }
        try { return Response.json({ status: "succeeded", workflow: name, result: await runWorkflow(name, input) }); }
        catch (e) { return Response.json({ status: "failed", workflow: name, error: String(e && e.message || e) }, { status: 500 }); }
      }
      return Response.json({ error: "not found", routes: ["GET /health", "POST /run/:workflow", "POST /hooks/:workflow"] }, { status: 404 });
    },
  });
  console.error("mill bundle '${projectName}' serving on http://localhost:" + server.port + " — POST /run/<workflow>");
  console.error("workflows: " + WORKFLOWS.join(", "));
}

const args = process.argv.slice(2);
if (args[0] === "serve") {
  serve(Number(args[1] || process.env.PORT || 8080));
} else {
  const [wf, inputJson] = args;
  runWorkflow(wf || ${JSON.stringify(defaultWf)}, inputJson ? JSON.parse(inputJson) : {})
    .then((r) => console.log(JSON.stringify(r)))
    .catch((e) => { console.error(String(e && e.message || e)); process.exit(1); });
}
`;
}

// Self-contained runner: it does EVERYTHING needed — checks for Bun, installs the bundle's
// npm deps on first run, then executes. Works from any cwd. Batch or server mode:
//   ./run.sh <workflow> '<json-input>'    ./run.sh serve [port]
const RUN_SH = `#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

# Load secrets from .env if present (copy .env.example → .env and fill it in). Each node still
# only sees the secret refs it declares.
if [ -f .env ]; then set -a; . ./.env; set +a; fi

if ! command -v bun >/dev/null 2>&1; then
  echo "This bundle needs Bun. Install it, then re-run:" >&2
  echo "  curl -fsSL https://bun.sh/install | bash" >&2
  exit 1
fi

# Install external dependencies once (no-op if the node code uses only the standard library).
if [ ! -f .mill-installed ]; then
  echo "mill: installing dependencies…" >&2
  bun install
  touch .mill-installed
fi

# Run: no args → first workflow (batch); "<workflow> '<json>'" → that workflow; "serve [port]" → HTTP API.
exec bun run index.js "$@"
`;

function readme(projectName: string, workflows: string[], secrets: string[]): string {
  const secretsBlock = secrets.length
    ? `## Secrets
This workload needs ${secrets.length} secret${secrets.length === 1 ? "" : "s"}: ${secrets.map((s) => `\`${s}\``).join(", ")}.
See **\`.env.example\`** for the full list (with which node uses each + example values):
\`\`\`bash
cp .env.example .env      # then fill in real values — run.sh loads .env automatically
\`\`\`
`
    : `## Secrets
This workload declares no secrets — nothing to configure (see \`.env.example\`).
`;
  return `# ${projectName} — exported from Mill

A standalone bundle. Runs the same compiled program Mill runs. **\`run.sh\` does everything
required** — it checks for Bun, installs npm dependencies on first run, then executes. You
only need Bun installed (\`curl -fsSL https://bun.sh/install | bash\`).

## Run (batch — some jobs just run)
\`\`\`bash
./run.sh ${workflows[0] ?? "workflow"} '{}'      # runs once, prints the result
./run.sh                          # runs the first workflow with {} input
\`\`\`

## Serve as an HTTP API (others expose a port)
\`\`\`bash
./run.sh serve 8080
curl -s localhost:8080/health                       # → { ok, workflows: [...] }
curl -s -XPOST localhost:8080/run/${workflows[0] ?? "workflow"} -d '{}'   # → { status, result }
\`\`\`
\`POST /run/<workflow>\` (alias \`/hooks/<workflow>\`) runs a workflow with the JSON body as
input — the same entrypoint a webhook trigger would hit.

${secretsBlock}
Workflows: ${workflows.join(", ")}.
Secrets are read from the environment (each node sees only the refs it declares).
`;
}

// A plausible placeholder value for a secret, inferred from its name — enough to make the
// .env.example self-documenting without ever emitting a real credential.
function exampleFor(name: string): string {
  const u = name.toUpperCase();
  if (/(URL|URI|ENDPOINT)$/.test(u)) return "https://api.example.com";
  if (/PORT$/.test(u)) return "8080";
  if (/EMAIL$/.test(u)) return "you@example.com";
  if (/(USERNAME|USER_ID|_ID|USER)$/.test(u)) return "your-" + name.toLowerCase().replace(/_/g, "-");
  if (/(ENABLED|DRY_RUN|DEBUG|VERBOSE)$/.test(u)) return "false";
  // KEY / TOKEN / SECRET / PASSWORD / AUTH / CREDENTIAL and everything else → a clear placeholder.
  return "changeme";
}

/**
 * Which secrets a project's workflows use. `declared` = a node's `secrets:` list (what the
 * runtime actually injects). `undeclared` = names referenced as `ctx.secrets.X` in node code
 * but NOT declared — those won't be injected (Mill scrubs each node to its declared refs), so
 * they're surfaced as a warning. Both map name → the "workflow/node" sites that use it.
 */
function collectSecrets(projectDir: string, wfNames: string[]): { declared: Map<string, Set<string>>; undeclared: Map<string, Set<string>> } {
  const declared = new Map<string, Set<string>>();
  const referenced = new Map<string, Set<string>>();
  const add = (m: Map<string, Set<string>>, name: string, site: string) => { (m.get(name) ?? m.set(name, new Set()).get(name)!).add(site); };
  for (const name of wfNames) {
    let loaded;
    try { loaded = loadWorkflow(projectDir, name); } catch { continue; }
    const { def, dir } = loaded;
    for (const n of def.nodes) {
      const site = `${name}/${n.key}`;
      for (const s of (n as { secrets?: string[] }).secrets ?? []) add(declared, s, site);
      const file = (n as { file?: string }).file;
      if ((n.kind === "jscode" || n.kind === "loop") && file) {
        try {
          const src = readFileSync(resolve(dir, file), "utf8");
          for (const m of src.matchAll(/\bctx\.secrets\.([A-Za-z_$][\w$]*)/g)) add(referenced, m[1], site);
          for (const m of src.matchAll(/\bctx\.secrets\[\s*["'`]([^"'`\]]+)["'`]\s*\]/g)) add(referenced, m[1], site);
        } catch { /* unreadable node file — skip */ }
      }
    }
  }
  const undeclared = new Map<string, Set<string>>();
  for (const [name, sites] of referenced) if (!declared.has(name)) undeclared.set(name, sites);
  return { declared, undeclared };
}

/** Render a .env.example documenting the secrets this bundle needs (with example values). */
function renderEnvExample(projectName: string, declared: Map<string, Set<string>>, undeclared: Map<string, Set<string>>): string {
  const lines = [
    `# .env.example — environment variables the "${projectName}" workflows use.`,
    `# Copy to .env and fill in real values, then run:   cp .env.example .env && ./run.sh`,
    `# (run.sh auto-loads .env; each node only sees the secret refs it declares.)`,
    ``,
  ];
  if (declared.size === 0 && undeclared.size === 0) {
    lines.push(`# This project declares no secrets — nothing to configure.`, ``);
    return lines.join("\n");
  }
  for (const name of [...declared.keys()].sort()) {
    lines.push(`# used by: ${[...declared.get(name)!].sort().join(", ")}`, `${name}=${exampleFor(name)}`, ``);
  }
  if (undeclared.size) {
    lines.push(
      `# ─────────────────────────────────────────────────────────────────────────`,
      `# Referenced in node code as ctx.secrets.* but NOT declared in the node's`,
      `# \`secrets:\` list — Mill will NOT inject these. Add them to the node's secrets`,
      `# in workflow.yaml if they're really needed, then re-export.`,
      ``,
    );
    for (const name of [...undeclared.keys()].sort()) {
      lines.push(`# referenced by: ${[...undeclared.get(name)!].sort().join(", ")}`, `# ${name}=${exampleFor(name)}`, ``);
    }
  }
  return lines.join("\n");
}

export async function exportProject(projectDir: string): Promise<{ tgz: Uint8Array; name: string }> {
  const proj = loadProject(projectDir);
  const wfNames = listWorkflows(projectDir);
  if (wfNames.length === 0) throw new Error("project has no workflows");

  const plans: Record<string, unknown> = {};
  const triggers: Record<string, string[]> = {};
  const imports: string[] = [];
  const nodeMap: string[] = [];
  const deps: Record<string, string> = {};
  let idx = 0;

  for (const name of wfNames) {
    const { def, dir } = loadWorkflow(projectDir, name);
    plans[name] = buildPlan(def);
    triggers[name] = (def.triggers ?? []).map((t) => t.type);
    for (const n of def.nodes) {
      // jscode nodes AND loop nodes with a per-item jscode body both import their .js file.
      if ((n.kind === "jscode" || n.kind === "loop") && n.file) {
        const v = `nfn${idx++}`;
        imports.push(`import ${v} from ${JSON.stringify(resolve(dir, n.file))};`);
        nodeMap.push(`  ${JSON.stringify(`${name}/${n.key}`)}: ${v},`);
      }
      if (n.deps) Object.assign(deps, n.deps);
    }
  }

  const tmp = mkdtempSync(join(tmpdir(), "mill-export-"));
  const out = mkdtempSync(join(tmpdir(), "mill-bundle-"));
  try {
    const entryPath = join(tmp, "entry.ts");
    writeFileSync(entryPath, generateEntry(proj.metadata.name, plans, imports, nodeMap, triggers, wfNames[0], SDK_PATH));

    const built = await Bun.build({ entrypoints: [entryPath], target: "bun", external: Object.keys(deps) });
    if (!built.success) throw new Error("bundle failed: " + built.logs.map((l) => String(l.message ?? l)).join("; "));
    const indexJs = await built.outputs[0].text();

    // Evaluate which secrets the workload needs → a self-documenting .env.example.
    const { declared, undeclared } = collectSecrets(projectDir, wfNames);

    writeFileSync(join(out, "index.js"), indexJs);
    writeFileSync(join(out, "package.json"), JSON.stringify({ name: proj.metadata.name, private: true, type: "module", dependencies: deps, scripts: { start: "bun run index.js", "start-server": "bun run index.js serve" } }, null, 2));
    writeFileSync(join(out, "run.sh"), RUN_SH, { mode: 0o755 });
    writeFileSync(join(out, ".env.example"), renderEnvExample(proj.metadata.name, declared, undeclared));
    writeFileSync(join(out, "README.md"), readme(proj.metadata.name, wfNames, [...declared.keys()].sort()));

    const tgzPath = join(out, "bundle.tgz");
    await Bun.spawn(["tar", "-czf", tgzPath, "-C", out, "index.js", "package.json", "run.sh", "README.md", ".env.example"]).exited;
    const tgz = new Uint8Array(await Bun.file(tgzPath).arrayBuffer());
    return { tgz, name: proj.metadata.name };
  } finally {
    rmSync(tmp, { recursive: true, force: true });
    rmSync(out, { recursive: true, force: true });
  }
}
